
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- LÍNEA MAQUILLAJE Y COLOR PROFESIONAL ---
    {
        id: 47252,
        name: "Pomada para Cejas THE ONE",
        brand: "The ONE",
        price: 8.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47252%2F47252_1.png",
        description: "Alcanza la perfección en tus cejas con esta pomada de alto rendimiento. Su innovadora fórmula cremosa se desliza con suavidad y se transforma en un polvo mate de larga duración al secarse. Diseñada para definir, rellenar y esculpir, permite crear desde un aspecto natural 'pelo a pelo' hasta un diseño bold y dramático. Es resistente al agua, al sudor y a la humedad, garantizando que tus cejas permanezcan impecables hasta por 24 horas sin emborronarse ni perder intensidad.",
        howToUse: "Utiliza un pincel biselado para cejas. Toma una pequeña cantidad de producto y comienza dibujando una línea fina en la parte inferior de la ceja. Rellena los huecos con trazos cortos hacia arriba y difumina con un cepillo tipo goupillon para un acabado profesional.",
        stock: 90,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 622,
        variants: {
            "Tono": [
                { value: "Blonde", colorCode: "#d9c5b2" },
                { value: "Brown", colorCode: "#6b4e3d" }
            ]
        }
    },
    {
        id: 47188,
        name: "Iluminador Líquido Illuskin THE ONE",
        brand: "The ONE",
        price: 9.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47188%2F47188_1.png",
        description: "El secreto de una piel radiante y 'dewy'. Este iluminador líquido concentrado utiliza la Tecnología Illuskin con pigmentos perlados que difunden la luz para suavizar visualmente las líneas de expresión y los poros, creando un halo de luz natural. Su fórmula ultra-ligera está enriquecida con Vitamina E antioxidante. Es extremadamente versátil: aporta un brillo focalizado si se aplica sobre los pómulos o un resplandor global si se mezcla con la base de maquillaje.",
        howToUse: "Aplica una o dos gotas directamente sobre los pómulos, el arco de cupido y el puente de la nariz. También puedes mezclar una gota con tu hidratante diaria o base de maquillaje para un acabado luminoso en todo el rostro.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 47
    },
    {
        id: 47977,
        name: "Brillo para Pestañas y Cejas Glitter THE ONE",
        brand: "The ONE",
        price: 8.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47977%2F47977_1.png",
        description: "Transforma tu look diario en un maquillaje festivo en segundos. Este gel transparente de fijación ligera contiene micro-partículas de purpurina de alta calidad que capturan la luz desde todos los ángulos. Su fórmula de secado rápido asegura que el glitter permanezca en su lugar sin caerse sobre las mejillas. Ideal para añadir un toque 'estelar' a las pestañas después de la máscara o para iluminar las cejas con un destello sofisticado. Sin sensación pegajosa.",
        howToUse: "Desliza el aplicador sobre las puntas de las pestañas ya maquilladas o peina las cejas siguiendo su dirección natural para depositar el brillo. Se retira fácilmente con cualquier desmaquillante.",
        stock: 80,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.6,
        reviewCount: 40
    },
    {
        id: 48650,
        name: "Máscara de Pestañas Winter Wonder Lash Waterproof",
        brand: "The ONE",
        price: 7.49,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48650%2F48650_1.png",
        description: "La icónica máscara 5 en 1 de Oriflame llega en una edición limitada de invierno con una fórmula resistente al agua de larga duración. Ofrece 5 beneficios extraordinarios: Volumen épico, Longitud increíble, Curvatura de infarto, Separación precisa y Cuidado intensivo. Su exclusivo cepillo Wonder Brush tiene cerdas largas para separar y cerdas cortas para depositar volumen desde la raíz. Enriquecida con pantenol para acondicionar las pestañas y evitar que se vuelvan quebradizas.",
        howToUse: "Comienza aplicando en la base de las pestañas con movimientos en zigzag y sube hasta las puntas. Utiliza las cerdas cortas para el volumen inicial y las largas para peinar y extender la longitud.",
        stock: 120,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 135
    },
    {
        id: 46134,
        name: "BB Cream Beautifier MAX SPF 15 THE ONE",
        brand: "The ONE",
        price: 7.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46134%2F46134_1.png",
        description: "Tu mejor aliada para un rostro perfecto con aspecto natural. Esta BB Cream multifuncional actúa como hidratante, prebase y base de cobertura ligera. Unifica el tono de la piel al instante, disimula rojeces y difumina poros, a la vez que proporciona una hidratación profunda que dura todo el día. Incluye SPF 15 para proteger tu piel contra los daños solares diarios. Su textura 'skin-fitting' se adapta perfectamente al relieve de tu piel para un acabado fresco, jugoso y sin imperfecciones.",
        howToUse: "Aplica una pequeña cantidad en el centro del rostro y extiéndela hacia fuera con las yemas de los dedos o una esponja de maquillaje. Puedes aplicar una segunda capa en zonas que necesiten más corrección.",
        stock: 289,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 339
    },
    {
        id: 46906,
        name: "Maquillaje Stress-Free Everlasting Sync SPF 20",
        brand: "The ONE",
        price: 9.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46906%2F46906_1.png",
        description: "La primera base de maquillaje inteligente de Oriflame que se sincroniza con tu piel y el entorno que te rodea. Gracias a su exclusiva Tecnología Skin Response, es capaz de absorber la humedad del ambiente cuando es excesiva o liberar hidratación si la piel está seca. Ofrece hasta 30 horas de duración con una cobertura media-alta modulable. Acabado semi-mate que resiste la humedad y el sudor. Contiene SPF 20 para una protección completa frente al envejecimiento prematuro.",
        howToUse: "Aplica sobre la piel limpia. Utiliza una brocha para una cobertura total o una esponja húmeda para un acabado más ligero y natural. Sellado instantáneo.",
        stock: 1105,
        category: "makeup",
        rating: 4.8,
        reviewCount: 1105
    },
    {
        id: 43245,
        name: "Maquillaje Eternal Glow SPF 25 Giordani Gold",
        brand: "Giordani Gold",
        price: 14.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43245%2FES%2F43245_1.png",
        description: "Lujo supremo y cuidado antiedad en cada gota. Esta base de maquillaje premium de Giordani Gold está infusionada con un potente Serum Potenciador de Juventud que contiene Ácido Hialurónico y Extracto de Azafrán. Su fórmula ligera proporciona una hidratación intensa y una luminosidad 'eterna' que parece nacer desde el interior. Mejora visiblemente la firmeza y elasticidad de la piel con el uso continuado, protegiéndola con SPF 25 y filtros UVA. Acabado radiante y sofisticado.",
        howToUse: "Agita suavemente antes de usar. Aplica con una brocha de maquillaje profesional empezando desde el centro del rostro hacia el exterior para una cobertura uniforme y lujosa.",
        stock: 1069,
        category: "makeup",
        rating: 4.8,
        reviewCount: 1069
    },

    // --- LÍNEA DE CUIDADO CORPORAL LUXURY (MILK & HONEY GOLD) ---
    {
        id: 47697,
        name: "Champú Nutritivo Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 6.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47697%2F47697_1.png",
        description: "Transforma tu rutina de lavado en un ritual de lujo. Este champú cremoso está formulado con extractos orgánicos de Leche y Miel que limpian delicadamente el cabello sin despojarlo de sus aceites naturales. La leche, rica en acondicionadores, suaviza la fibra capilar, mientras que la miel atrae y retiene la humedad para un brillo espectacular. Su fragancia icónica y envolvente te acompañará durante todo el día, dejando tu melena manejable, nutrida y con un aspecto saludable.",
        howToUse: "Aplica sobre el cabello mojado, masajea suavemente el cuero cabelludo hasta crear una espuma rica y aclara con abundante agua tibia. Para mejores resultados, sigue con el acondicionador de la misma línea.",
        stock: 300,
        category: "hair",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 150
    },
    {
        id: 47698,
        name: "Acondicionador Nutritivo Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 6.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47698%2F47698_1.png",
        description: "El complemento perfecto para una melena de seda. Este acondicionador ultra-cremoso desenreda instantáneamente el cabello, reduciendo el encrespamiento y las puntas abiertas. Su rica fórmula con proteínas de leche y néctar de miel orgánica penetra en la cutícula capilar para restaurar la suavidad y elasticidad perdida. Ideal para cabellos secos o castigados que buscan recuperar su vitalidad natural y un brillo dorado inigualable.",
        howToUse: "Después del champú, aplica el acondicionador de medios a puntas. Deja actuar durante 2-3 minutos y aclara bien. Sentirás el cabello más suave al tacto inmediatamente.",
        stock: 250,
        category: "hair",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 120
    },
    {
        id: 46968,
        name: "Crema para Manos y Cuerpo Milk & Honey Gold Original",
        brand: "Milk & Honey Gold",
        price: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46968%2F46968_1.png",
        description: "El producto más deseado y vendido de Oriflame. Una crema corporal de textura fundente y ultra-rica que proporciona una nutrición intensiva durante 24 horas. Formulada con extractos de leche y miel de origen orgánico, calma las pieles más secas, restaurando su barrera protectora y dejándola increíblemente suave y elástica. Su aroma legendario es una mezcla cálida y reconfortante que invita al bienestar. Se absorbe con facilidad dejando un acabado aterciopelado sin sensación grasa.",
        howToUse: "Masajea generosamente sobre la piel limpia después del baño o la ducha, prestando especial atención a zonas secas como codos, rodillas y talones. Úsala a diario para una piel de lujo.",
        stock: 4028,
        category: "personal-care",
        rating: 4.9,
        reviewCount: 4028
    },
    {
        id: 46969,
        name: "Exfoliante Corporal de Azúcar Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46969%2F46969_1.png",
        description: "Revela la luminosidad oculta de tu piel con este tratamiento exfoliante de lujo. Contiene partículas naturales de azúcar que eliminan con suavidad las células muertas y las impurezas acumuladas en la superficie. Los extractos nutritivos de leche y miel aseguran que la piel no se irrite durante el proceso, quedando renovada, hidratada y extremadamente suave. Es el paso esencial antes de aplicar tu crema hidratante o autobronceador para un resultado uniforme y duradero.",
        howToUse: "Aplica sobre la piel húmeda 1 o 2 veces por semana. Masajea con movimientos circulares por todo el cuerpo y aclara. Notarás la piel renovada al instante.",
        stock: 1202,
        category: "personal-care",
        rating: 4.9,
        reviewCount: 1202
    },
    {
        id: 47536,
        name: "Crema Manos y Cuerpo Majestic Magnolia M&H",
        brand: "Milk & Honey Gold",
        price: 11.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47536%2F47536_1.png",
        description: "Una edición limitada de coleccionista que eleva la línea Milk & Honey Gold a nuevas cotas de sofisticación. Esta crema combina la nutrición legendaria de la leche y la miel con el aroma etéreo de la Magnolia Majestuosa. Su fragancia floral blanca y fresca se entrelaza con el dulzor de la miel para una experiencia sensorial única. Contiene manteca de karité para una hidratación profunda y pigmentos minerales que aportan un brillo sutil y elegante a la piel.",
        howToUse: "Ideal para usar por la mañana y por la noche. Aplica una cantidad generosa y disfruta de su perfume floral mientras se funde con tu piel.",
        stock: 635,
        category: "personal-care",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 635
    },
    {
        id: 47538,
        name: "Jabón en Barra Majestic Magnolia M&H",
        brand: "Milk & Honey Gold",
        price: 3.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47538%2F47538_1.png",
        description: "Limpia y perfuma tu piel con esta exclusiva barra de jabón de edición limitada. Su fórmula cremosa genera una espuma rica y abundante que elimina impurezas sin resecar, dejando la piel hidratada gracias a la glicerina y los extractos de miel. El aroma a magnolia aporta una sensación de frescura y feminidad en cada uso. Su diseño grabado la convierte también en un detalle perfecto para regalar o decorar tu baño.",
        howToUse: "Frota la barra entre las manos mojadas para crear espuma. Aplica sobre el cuerpo y aclara bien.",
        stock: 219,
        category: "personal-care",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 219
    },
    {
        id: 47537,
        name: "Jabón Líquido Manos Majestic Magnolia M&H",
        brand: "Milk & Honey Gold",
        price: 11.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47537%2F47537_1.png",
        description: "Eleva la higiene diaria de tus manos a un nivel superior. Este jabón líquido nutritivo limpia eficazmente mientras cuida la delicada piel de las manos, previniendo la sequedad causada por los lavados frecuentes. Enriquecido con el aroma sofisticado de la magnolia y la riqueza de la miel orgánica. Sus agentes hidratantes dejan las manos suaves, tersas y delicadamente perfumadas. Envase con dosificador para una aplicación cómoda y limpia.",
        howToUse: "Aplica una dosis sobre las manos húmedas, frota bien durante 20 segundos incluyendo entre los dedos y aclara con agua.",
        stock: 312,
        category: "personal-care",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 312
    },
    {
        id: 46970,
        name: "Crema de Ducha Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46970%2F46970_1.png",
        description: "Convierte tu ducha diaria en un spa personal. Este gel de ducha de textura cremosa y untuosa envuelve tu cuerpo en una espuma hidratante que respeta el equilibrio natural de tu piel. Formulada con extractos orgánicos de leche y miel, limpia suavemente mientras deposita una capa de hidratación que notarás incluso después de secarte. La piel queda flexible, fresca y con el reconfortante aroma clásico de la colección Gold.",
        howToUse: "Aplica sobre la piel mojada con una esponja o directamente con las manos. Masajea por todo el cuerpo y aclara. Sentirás la piel suave como la seda.",
        stock: 1356,
        category: "personal-care",
        rating: 4.9,
        reviewCount: 1356
    },
    {
        id: 46971,
        name: "Jabón en Barra Milk & Honey Gold Original",
        brand: "Milk & Honey Gold",
        price: 6.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46971%2F46971_1.png",
        description: "El jabón tradicional, perfeccionado. Esta barra ultra-nutritiva está diseñada para limpiar el rostro y el cuerpo sin agredir la piel. Rica en extractos naturales de leche y miel, ayuda a suavizar las zonas más ásperas y mantiene la hidratación cutánea. Su espuma es densa y aterciopelada, proporcionando una limpieza profunda que deja la piel con una sensación de frescura y nutrición duradera. Un básico indispensable de tocador.",
        howToUse: "Humedecer la piel y la barra de jabón, frotar hasta obtener espuma y masajear suavemente. Aclarar con agua.",
        stock: 931,
        category: "personal-care",
        rating: 4.9,
        reviewCount: 931
    },

    // --- ACCESORIOS Y HERRAMIENTAS DE BELLEZA ---
    {
        id: 48573,
        name: "Rizador de Pestañas Magical Midnights",
        brand: "Oriflame",
        price: 3.49,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48573%2F48573_1.png",
        description: "Logra una mirada abierta e impactante con este rizador de pestañas ergonómico. Parte de la exclusiva colección Magical Midnights, cuenta con un acabado metalizado de alta gama. Su almohadilla de silicona suave protege las pestañas de roturas o tirones, permitiendo aplicar la presión justa para una curvatura perfecta y duradera. Su diseño se adapta a la mayoría de las formas de ojos para llegar incluso a las pestañas de los extremos.",
        howToUse: "Úsalo siempre antes de aplicar la máscara de pestañas. Coloca el rizador cerca de la raíz de las pestañas, presiona suavemente durante 5-10 segundos y suelta. Repite si deseas más intensidad.",
        stock: 13,
        category: "accessories",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 13
    },
    {
        id: 41760,
        name: "Stick de Aceite para Uñas y Cutículas THE ONE",
        brand: "The ONE",
        price: 4.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41760%2F41760_1.png",
        description: "Manicura perfecta estés donde estés. Este innovador stick de aceite nutritivo está formulado con Aceite de Almendras Dulces, Aceite de Girasol y Vitamina E. Su práctico formato en barra permite una aplicación precisa y sin derrames, ideal para llevar en el bolso. Hidrata profundamente las cutículas secas y endurecidas, a la vez que fortalece las uñas débiles, promoviendo un crecimiento más sano y flexible. Resultados visibles desde la primera aplicación.",
        howToUse: "Gira el extremo del stick y desliza el aplicador sobre las cutículas y las uñas limpias. Masajea ligeramente con los dedos para favorecer la absorción.",
        stock: 660,
        category: "makeup",
        rating: 4.8,
        reviewCount: 660
    },
    {
        id: 48978,
        name: "Limpiador de Brochas de Maquillaje Spray",
        brand: "Oriflame",
        price: 4.29,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48978%2F48978_1.png",
        description: "Mantén tus herramientas de belleza libres de bacterias y restos de maquillaje. Este spray limpiador de secado ultra-rápido es esencial para una higiene facial correcta. Su fórmula eficaz disuelve instantáneamente bases, sombras y labiales acumulados en las cerdas, permitiendo volver a usar las brochas en cuestión de minutos. Su uso regular prolonga la vida útil de tus pinceles y asegura que la aplicación del maquillaje sea siempre impecable y libre de impurezas.",
        howToUse: "Pulveriza directamente sobre las cerdas de la brocha y frótala suavemente sobre un paño limpio o papel absorbente hasta que no queden restos de color. No necesita aclarado.",
        stock: 43,
        category: "accessories",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 43
    },
    {
        id: 40672,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash XXL High",
        brand: "The ONE",
        price: 7.49,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40672%2F40672_1.png",
        description: "Nuestra máscara de pestañas más vendida, ahora potenciada para un volumen XXL. Con la exclusiva tecnología Pro-Lash, esta máscara cuida tus pestañas mientras las transforma. Ofrece volumen masivo, longitud infinita, curvatura extrema, definición pelo a pelo y nutrición profunda. Su cepillo patentado de doble cara deposita la cantidad justa de producto sin dejar grumos. Consigue una mirada de impacto que se mantiene intacta durante todo el día sin emborronarse.",
        howToUse: "Usa el lado de cerdas cortas para aplicar volumen y el lado de cerdas largas para extender y definir. Aplica varias capas para un efecto aún más dramático.",
        stock: 1550,
        category: "makeup",
        rating: 4.8,
        reviewCount: 1550
    },
    {
        id: 48565,
        name: "Jabonera Magnolia",
        brand: "Oriflame",
        price: 14.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48565%2F48565_1.png",
        description: "Complementa tu ritual de belleza con este accesorio exclusivo. Una jabonera de diseño elegante y atemporal inspirada en la pureza de la magnolia. Fabricada con materiales de alta calidad, cuenta con ranuras de drenaje para mantener tu jabón en barra siempre seco y prolongar su duración. Su acabado sofisticado aporta un toque de distinción a cualquier baño, siendo el soporte perfecto para las barras de la línea Milk & Honey Gold.",
        howToUse: "Coloca tu barra de jabón favorita sobre la jabonera después de cada uso para permitir que se seque correctamente al aire.",
        stock: 105,
        category: "accessories",
        tag: "NOVEDAD",
        rating: 5.0,
        reviewCount: 105
    }
];
