
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- PRODUCTO SOLICITADO COMO EJEMPLO PARA CSV ---
    {
        id: 44962,
        name: "Exfoliante Purificante Cuero Cabelludo DUOLOGI",
        brand: "DUOLOGI",
        price: 9.99,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44962%2F44962_1.png",
        description: "Exfoliante refrescante para el cuero cabelludo que elimina la acumulación de productos, grasa y caspa, revitalizando el cabello desde la raíz. Con ácido salicílico.",
        stock: 50,
        category: "hair",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 30,
        howToUse: "Úsalo una vez a la semana. Aplícalo sobre el cuero cabelludo mojado, masajea suavemente hasta formar espuma y aclara."
    },
    // --- MAQUILLAJE & NOVEDADES (Desde tu HTML) ---
    {
        id: 47188,
        name: "Iluminador Líquido Illuskin THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47188%2F47188_1.png",
        description: "Iluminador líquido versátil para un brillo natural o intenso. Mezclable y modulable.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.2,
        reviewCount: 5
    },
    {
        id: 46134,
        name: "BB Cream Beautifier MAX SPF 15 THE ONE",
        brand: "The ONE",
        price: 5.77,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46134%2F46134_1.png",
        description: "BB Cream multifuncional que hidrata, corrige y protege. Acabado natural.",
        stock: 289,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 289,
        variants: {
            "Tono": [
                { value: "Fair", colorCode: "#F3D8C8" },
                { value: "Light", colorCode: "#EBC9B4" },
                { value: "Medium", colorCode: "#D8AD94" },
                { value: "Dark", colorCode: "#B68266" }
            ]
        }
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "Giordani Gold",
        price: 16.93,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png",
        description: "Perlas bronceadoras infusionadas con serum antiedad. Edición limitada.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 82
    },
    {
        id: 46940,
        name: "Stick Iluminador con Color THE ONE",
        brand: "The ONE",
        price: 7.69,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46940%2F46940_1.png",
        description: "Iluminador en barra fácil de aplicar para un brillo radiante al instante.",
        stock: 80,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 552,
        variants: {
            "Tono": [
                { value: "Hot Pink", colorCode: "#E88DA3" },
                { value: "Coral", colorCode: "#EE9D8A" },
                { value: "Bronze", colorCode: "#C68E73" },
                { value: "Champagne", colorCode: "#F2D8C6" }
            ]
        }
    },
    {
        id: 46906,
        name: "Maquillaje Stress-Free Everlasting Sync SPF 20 + Protección UVA Natural THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46906%2F46906_1.png",
        description: "Base de maquillaje inteligente que se adapta a tu piel y al entorno.",
        stock: 75,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 1038,
        variants: {
            "Tono": [
                { value: "Alabaster", colorCode: "#F7E6D9" },
                { value: "Porcelain", colorCode: "#F1D9C8" },
                { value: "Ivory", colorCode: "#EDD0BE" },
                { value: "Beige", colorCode: "#E2C0A8" },
                { value: "Sun", colorCode: "#D9A683" },
                { value: "Amber", colorCode: "#C8926F" }
            ]
        }
    },
    {
        id: 42121,
        name: "Paleta de Ojos y Rostro Fabulous Beauty Giordani Gold",
        brand: "Giordani Gold",
        price: 19.24,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42121%2F42121_1.png",
        description: "Paleta todo en uno de lujo para ojos y rostro. Pigmentación intensa y sedosa.",
        stock: 40,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 371
    },
    {
        id: 42102,
        name: "Maquillaje Mineral de Larga Duración SPF 20 Giordani Gold",
        brand: "Giordani Gold",
        price: 13.08,
        regularPrice: 31.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42102%2F42102_1.png",
        description: "Base mineral de larga duración con cobertura completa y acabado luminoso.",
        stock: 60,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1066,
        variants: {
            "Tono": [
                { value: "Light Rose", colorCode: "#F3D3C6" },
                { value: "Light Ivory", colorCode: "#EFCEBF" },
                { value: "Rose Beige", colorCode: "#E6BCA9" },
                { value: "Natural Beige", colorCode: "#E2B5A2" }
            ]
        }
    },
    {
        id: 41107,
        name: "Corrector y Serum Potenciador Giordani Gold",
        brand: "Giordani Gold",
        price: 8.46,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41107%2FES%2F41107_1.png",
        description: "Corrector que borra imperfecciones mientras trata la piel con su serum.",
        stock: 50,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1053,
        variants: {
            "Tono": [
                { value: "Light", colorCode: "#F1D5C5" },
                { value: "Medium", colorCode: "#E2BC9F" }
            ]
        }
    },

    // --- CUIDADO DE LA PIEL & NOVAGE+ (Segundo bloque HTML) ---
    {
        id: 47847,
        name: "Lote Ritual de Cuidado de la Piel Wellosophy",
        brand: "Wellosophy",
        price: 53.89,
        regularPrice: 101.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47847%2F47847_1.png",
        description: "Rutina completa para el bienestar de tu piel desde el interior y el exterior.",
        stock: 62,
        category: "wellness",
        tag: "SET",
        rating: 4.7,
        reviewCount: 62,
        beautyPoints: 50
    },
    {
        id: 47785,
        name: "Lote Antioxidante Wellosophy",
        brand: "Wellosophy",
        price: 102.41,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47785%2F47785_1.png",
        description: "Protección antioxidante avanzada para combatir los radicales libres.",
        stock: 16,
        category: "wellness",
        tag: "SET",
        rating: 4.7,
        reviewCount: 16,
        beautyPoints: 95
    },
    {
        id: 46319,
        name: "Niacinamida 10% Power Drops Proceuticals Novage+",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46319%2F46319_1.png",
        description: "Potenciador con Niacinamida para fortalecer la barrera cutánea y mejorar la textura.",
        stock: 160,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 160
    },
    {
        id: 48675,
        name: "Caja de Regalo Crema Universal - Edición Especial",
        brand: "Crema Universal",
        price: 13.85,
        regularPrice: 36.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48675%2F48675_1.png",
        description: "Trío de cremas universales: Grosella Negra, Original y Ciruela Dulce.",
        stock: 100,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 5.0,
        reviewCount: 2
    },
    {
        id: 48105,
        name: "Mascarilla Revitalizante Intensiva Acción Noche Novage+",
        brand: "Novage+",
        price: 20.78,
        regularPrice: 39.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48105%2F48105_1.png",
        description: "Mascarilla nocturna intensiva para una piel revitalizada al despertar.",
        stock: 80,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 45
    },
    {
        id: 48117,
        name: "Crema de Noche Reafirmante Royal Velvet - Edición Especial",
        brand: "Royal Velvet",
        price: 18.47,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48117%2F48117_1.png",
        description: "Crema de noche rica en infusión de Iris Negro para reafirmar la piel madura.",
        stock: 55,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 1250
    },
    {
        id: 48115,
        name: "Crema de Día Reafirmante SPF 20 Royal Velvet",
        brand: "Royal Velvet",
        price: 18.47,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48115%2F48115_1.png",
        description: "Crema de día reafirmante que hidrata y protege la piel.",
        stock: 12,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 1300
    },
    {
        id: 48114,
        name: "Cápsulas Restauradoras con Aceites Naturales Novage+",
        brand: "Novage+",
        price: 32.33,
        regularPrice: 65.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48114%2F48114_1.png",
        description: "Mezcla de aceites preciosos en cápsulas monodosis para nutrir la piel.",
        stock: 8,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 668
    },
    {
        id: 48649,
        name: "Crema Universal Original - Edición Especial",
        brand: "Crema Universal",
        price: 5.38,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48649%2F48649_1.png",
        description: "La fórmula original icónica que suaviza y protege la piel seca.",
        stock: 727,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 5.0,
        reviewCount: 727
    },
    {
        id: 45147,
        name: "Serum Facial de Aceite Reafirmante y Relajante Wellosophy",
        brand: "Wellosophy",
        price: 26.95,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45147%2F45147_1.png",
        description: "Aceite facial ligero que reafirma y relaja la piel estresada.",
        stock: 142,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 142
    },
    {
        id: 45248,
        name: "Serum Even Out Optimals",
        brand: "Optimals",
        price: 13.85,
        regularPrice: 30.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45248%2F45248_1.png",
        description: "Serum que reduce la apariencia de manchas oscuras y unifica el tono.",
        stock: 317,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 317
    },
    {
        id: 45245,
        name: "Crema Hidratante Rica Even Out Optimals",
        brand: "Optimals",
        price: 10.00,
        regularPrice: 27.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45245%2F45245_1.png",
        description: "Hidratante rica que ayuda a prevenir manchas y nutre la piel.",
        stock: 222,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 222
    },
    {
        id: 47439,
        name: "Crema Universal con Ciruela Dulce",
        brand: "Crema Universal",
        price: 4.84,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47439%2F47439_1.png",
        description: "Edición limitada con delicioso aroma a ciruela dulce.",
        stock: 1618,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 1618
    },
    {
        id: 45291,
        name: "Contorno de Ojos y Labios Optimals",
        brand: "Optimals",
        price: 12.31,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45291%2F45291_1.png",
        description: "Cuidado reafirmante para la delicada zona de ojos y labios.",
        stock: 436,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 436
    },
    {
        id: 44098,
        name: "Tratamiento de Día SPF 30 Multi-Correcting Restore Novage+",
        brand: "Novage+",
        price: 19.24,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44098%2F44098_1.png",
        description: "Crema de día multi-correctora con SPF 30. Combate los signos del envejecimiento.",
        stock: 839,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 839
    },
    {
        id: 44285,
        name: "Tratamiento de Noche Multi-Recover Restore Novage+",
        brand: "Novage+",
        price: 19.24,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44285%2F44285_1.png",
        description: "Crema de noche reparadora que activa la recuperación nocturna de la piel.",
        stock: 668,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 668
    },
    {
        id: 41075,
        name: "Serum Renewing Restore Novage+",
        brand: "Novage+",
        price: 29.25,
        regularPrice: 64.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41075%2F41075_1.png",
        description: "Serum renovador que mejora la elasticidad y reduce arrugas profundas.",
        stock: 664,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 664
    },
    {
        id: 41070,
        name: "Contorno de Ojos y Labios Renewing Restore Novage+",
        brand: "Novage+",
        price: 13.08,
        regularPrice: 38.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41070%2F41070_1.png",
        description: "Contorno de ojos avanzado para restaurar la firmeza.",
        stock: 504,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 504
    },
    {
        id: 45292,
        name: "Multi-Protector SPF 50 Daily Glow Optimals",
        brand: "Optimals",
        price: 10.00,
        regularPrice: 29.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45292%2F45292_1.png",
        description: "Protección solar alta con acabado luminoso para uso diario.",
        stock: 738,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 738
    },
    {
        id: 45243,
        name: "Crema Hidratante Ligera Even Out Optimals",
        brand: "Optimals",
        price: 10.00,
        regularPrice: 27.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45243%2F45243_1.png",
        description: "Hidratante ligera que unifica el tono y matifica la piel.",
        stock: 204,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 204
    },
    {
        id: 46989,
        name: "Crema Universal con Mandarina Dulce",
        brand: "Crema Universal",
        price: 5.38,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46989%2FES%2F46989_1.png",
        description: "Edición especial con extracto de mandarina. Suaviza y protege.",
        stock: 2295,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 2295
    },
    {
        id: 41059,
        name: "Fluido Ultraligero Alta Protección SPF 50 Proceuticals Novage+",
        brand: "Novage+",
        price: 16.16,
        regularPrice: 30.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41059%2F41059_1.png",
        description: "Escudo protector invisible contra rayos UVA/UVB y contaminación.",
        stock: 1888,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 1888
    },
    {
        id: 41032,
        name: "Limpiadora Oleosa Comfort Novage+",
        brand: "Novage+",
        price: 16.93,
        regularPrice: 30.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41032%2F41032_1.png",
        description: "Limpiadora en aceite que disuelve el maquillaje y las impurezas al instante.",
        stock: 510,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 510
    },
    {
        id: 47437,
        name: "Parches Faciales de Gel Hydra-Glow Optimals",
        brand: "Optimals",
        price: 4.23,
        regularPrice: 12.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47437%2F47437_1.png",
        description: "Parches refrescantes para hidratar y revitalizar la zona de los ojos.",
        stock: 0,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.7,
        reviewCount: 196
    },
    {
        id: 34849,
        name: "Aceite Purificante con Árbol de Té y Lima Love Nature",
        brand: "Love Nature",
        price: 6.54,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F34849%2F34849_1.png",
        description: "Aceite concentrado para combatir imperfecciones y purificar la piel.",
        stock: 1783,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1783
    },
    {
        id: 41037,
        name: "Serum Lift + Firm Novage+",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 58.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41037%2F41037_1.png",
        description: "Serum lifting que redefine el óvalo facial y mejora la firmeza.",
        stock: 583,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 583
    },
    {
        id: 47102,
        name: "Retinol Power Drops Proceuticals Novage+",
        brand: "Novage+",
        price: 23.09,
        regularPrice: 44.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47102%2F47102_1.png",
        description: "Tratamiento intensivo con Retinol encapsulado para reducir arrugas.",
        stock: 421,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 421
    },
    {
        id: 40670,
        name: "Prebase Perfeccionadora Woke Up Like This Waunt",
        brand: "Waunt",
        price: 13.85,
        regularPrice: 27.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40670%2FES%2F40670_1.png",
        description: "Prebase híbrida que ilumina y perfecciona la piel al instante.",
        stock: 418,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 418
    },
    {
        id: 41035,
        name: "Serum Wrinkle Smooth Novage+",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 58.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41035%2F41035_1.png",
        description: "Serum antiarrugas avanzado que suaviza la textura de la piel.",
        stock: 395,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 395
    },
    {
        id: 41040,
        name: "Serum Bright Intense",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 58.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41040%2F41040_1.png",
        description: "Serum iluminador que reduce manchas y mejora la luminosidad.",
        stock: 338,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 338
    },
    {
        id: 48678,
        name: "Parches Exfoliantes y Limpiadores Proceuticals Novage+",
        brand: "Novage+",
        price: 3.84,
        regularPrice: 9.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48678%2F48678_1.png",
        description: "Discos exfoliantes de doble cara para una piel suave y radiante.",
        stock: 271,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 271
    },
    {
        id: 45326,
        name: "Crema Hidratante SPF 25 The Beyond Optimals",
        brand: "Optimals",
        price: 18.47,
        regularPrice: 36.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45326%2F45326_1.png",
        description: "Hidratante diaria con protección SPF 25 para todo tipo de pieles.",
        stock: 358,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 358
    },
    {
        id: 46900,
        name: "Limpiador Soft Creamy Optimals",
        brand: "Optimals",
        price: 8.46,
        regularPrice: 19.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46900%2F46900_1.png",
        description: "Limpiadora en crema suave que elimina impurezas sin resecar.",
        stock: 576,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 576
    },
    {
        id: 46992,
        name: "Mascarilla Facial Iluminadora Gel to Ice con Mango Orgánico Love Nature",
        brand: "Love Nature",
        price: 2.30,
        regularPrice: 6.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46992%2F46992_1.png",
        description: "Mascarilla refrescante de mango para una piel radiante.",
        stock: 468,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 468
    },
    {
        id: 46990,
        name: "Mascarilla Facial Hidratante Gel to Ice con Sandía Orgánica Love Nature",
        brand: "Love Nature",
        price: 2.30,
        regularPrice: 6.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46990%2F46990_1.png",
        description: "Mascarilla hidratante de sandía. Úsala fría para un efecto calmante.",
        stock: 567,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 567
    },
    // --- NUEVOS PRODUCTOS AÑADIDOS PARA OFERTAS PAGE ---
    {
        id: 47977,
        name: "Brillo para Pestañas y Cejas Glitter THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47977%2F47977_1.png&MediaId=20570089&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Toque de brillo festivo para pestañas y cejas.",
        stock: 80,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 4,
    },
    {
        id: 48650,
        name: "Máscara de Pestañas Winter Wonder Lash Waterproof THE ONE",
        brand: "The ONE",
        price: 5.38,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48650%2F48650_1.png&MediaId=20570152&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Máscara 5 en 1 a prueba de agua, edición de invierno.",
        stock: 120,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 16,
    },
    {
        id: 47253,
        name: "Pomada para Cejas THE ONE",
        brand: "The ONE",
        price: 5.38,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47253%2F47253_1.png&MediaId=20250127&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Pomada de alta pigmentación para definir y rellenar las cejas.",
        stock: 90,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 551,
        variants: {
            'Tono': [
                { value: 'Brown', colorCode: '#6b4e3d' },
                { value: 'Dark Brown', colorCode: '#3e2c22' }
            ]
        }
    },
    {
        id: 46929,
        name: "Sombra de Ojos Colour Unlimited THE ONE",
        brand: "The ONE",
        price: 5.38,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46929%2F46929_1.png&MediaId=20181760&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Sombra de ojos en stick de larga duración.",
        stock: 200,
        category: 'makeup',
        rating: 4.8,
        reviewCount: 1490,
    },
    {
        id: 48039,
        name: "Máscara de Pestañas Hypnotic Colour THE ONE",
        brand: "The ONE",
        price: 6.15,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48039%2F48039_1.png&MediaId=20301795&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Máscara de pestañas de color intenso.",
        stock: 120,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 412
    },
    {
        id: 46888,
        name: "Rotulador de Labios Stain & Stay THE ONE",
        brand: "The ONE",
        price: 5.77,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46888%2F46888_1.png&MediaId=20030909&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Tinte de labios en formato rotulador de larga duración.",
        stock: 85,
        category: 'makeup',
        rating: 4.4,
        reviewCount: 748,
    },
    {
        id: 47704,
        name: "Delineador de Ojos High Impact THE ONE",
        brand: "The ONE",
        price: 4.23,
        regularPrice: 13.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47704%2F47704_1.png&MediaId=20324587&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Delineador de ojos de alto impacto y precisión.",
        stock: 150,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 675
    },
    {
        id: 47180,
        name: "Bálsamo de Labios Smooth Like Butter Waunt",
        brand: "Waunt",
        price: 7.69,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47180%2F47180_1.png&MediaId=19970405&Version=4&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Bálsamo labial ultra nutritivo con efecto manteca.",
        stock: 90,
        category: 'skincare',
        rating: 4.8,
        reviewCount: 592
    },
    {
        id: 47192,
        name: "Sombra de Ojos Líquida THE ONE",
        brand: "The ONE",
        price: 6.92,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47192%2F47192_1.png&MediaId=20325039&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Sombra líquida metálica de alto brillo.",
        stock: 80,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.6,
        reviewCount: 173
    },
    {
        id: 48640,
        name: "Barra de Labios Líquida Glitter THE ONE",
        brand: "The ONE",
        price: 9.23,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48640%2F48640_1.png&MediaId=20570134&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Labial líquido con acabado glitter espectacular.",
        stock: 70,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.6,
        reviewCount: 21
    },
    {
        id: 43244,
        name: "Maquillaje Eternal Glow SPF 25 Giordani Gold",
        brand: "Giordani Gold",
        price: 16.16,
        regularPrice: 32.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43244%2FES%2F43244_1.png&MediaId=18142025&Version=8&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Base iluminadora para un brillo eterno.",
        stock: 80,
        category: 'makeup',
        rating: 4.8,
        reviewCount: 1027
    },
    {
        id: 41760,
        name: "Stick de Aceite para Uñas y Cutículas THE ONE Expert",
        brand: "The ONE",
        price: 4.61,
        regularPrice: 10.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41760%2F41760_1.png&MediaId=14318005&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Cuidado nutritivo para uñas y cutículas en formato stick.",
        stock: 200,
        category: 'personal-care',
        rating: 4.8,
        reviewCount: 641
    },
    {
        id: 42652,
        name: "Barra de Labios Iconic Satin SPF 15 Giordani Gold",
        brand: "Giordani Gold",
        price: 9.23,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42652%2F42652_1.png&MediaId=18837652&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Labial satinado de lujo con SPF 15.",
        stock: 150,
        category: 'makeup',
        rating: 4.8,
        reviewCount: 450
    },
    {
        id: 44835,
        name: "Polvos Compactos con Serum Giordani Gold",
        brand: "Giordani Gold",
        price: 13.08,
        regularPrice: 26.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44835%2F44835_1.png&MediaId=19278494&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Polvos compactos sedosos con beneficios antiedad.",
        stock: 100,
        category: 'makeup',
        rating: 4.8,
        reviewCount: 372
    },
    {
        id: 34647,
        name: "Polvos Compactos Everlasting THE ONE",
        brand: "The ONE",
        price: 9.23,
        regularPrice: 19.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F34647%2F34647_1.png&MediaId=14800970&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Polvos matificantes de larga duración.",
        stock: 180,
        category: 'makeup',
        rating: 4.8,
        reviewCount: 329
    },
    {
        id: 46588,
        name: "Brillo de Labios Oh! Sweet Glossy OnColour",
        brand: "OnColour",
        price: 2.69,
        regularPrice: 4.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46588%2F46588_1.png&MediaId=18704766&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Brillo labial dulce y brillante.",
        stock: 250,
        category: 'makeup',
        rating: 4.7,
        reviewCount: 1388
    },
    {
        id: 37728,
        name: "Perfilador de Labios Ultimate THE ONE",
        brand: "The ONE",
        price: 4.23,
        regularPrice: 13.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F37728%2F37728_1.png&MediaId=13799751&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Perfilador de labios retráctil de alta definición.",
        stock: 130,
        category: 'makeup',
        rating: 4.7,
        reviewCount: 1226
    },
    {
        id: 46611,
        name: "Barra de Labios Cremosa OnColour (Tono 1)",
        brand: "OnColour",
        price: 1.92,
        regularPrice: 5.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46611%2F46611_1.png&MediaId=18840964&Version=5&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Labial cremoso con colores vibrantes.",
        stock: 300,
        category: 'makeup',
        rating: 4.7,
        reviewCount: 718
    },
    {
        id: 46549,
        name: "Máscara de Pestañas False Lashes Salon Lift THE ONE",
        brand: "The ONE",
        price: 6.92,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46549%2F46549_1.png&MediaId=18810797&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Efecto pestañas postizas con elevación de salón.",
        stock: 140,
        category: 'makeup',
        rating: 4.7,
        reviewCount: 707
    },
    {
        id: 46601,
        name: "Barra de Labios Cremosa OnColour (Tono 2)",
        brand: "OnColour",
        price: 1.92,
        regularPrice: 5.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46601%2FES%2F46601_1.png&MediaId=18220588&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Labial cremoso para uso diario.",
        stock: 200,
        category: 'makeup',
        rating: 4.7,
        reviewCount: 690
    },
    {
        id: 45361,
        name: "Sombra de Ojos Líquida Metallic THE ONE",
        brand: "The ONE",
        price: 6.54,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45361%2FES%2F45361_1.png&MediaId=18267832&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Sombra líquida de acabado metálico.",
        stock: 100,
        category: 'makeup',
        rating: 4.7,
        reviewCount: 649
    },
    {
        id: 38690,
        name: "Barra de Labios Cremosa OnColour (Tono 3)",
        brand: "OnColour",
        price: 1.92,
        regularPrice: 5.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38690%2FES%2F38690_1.png&MediaId=18220058&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Labial hidratante y suave.",
        stock: 220,
        category: 'makeup',
        rating: 4.7,
        reviewCount: 536
    },
    {
        id: 46595,
        name: "Gel para Cejas Lift & Fix THE ONE",
        brand: "The ONE",
        price: 6.54,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46595%2F46595_1.png&MediaId=18715133&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Gel fijador transparente para cejas.",
        stock: 110,
        category: 'makeup',
        rating: 4.7,
        reviewCount: 494
    },
    {
        id: 38991,
        name: "Esmalte de Uñas OnColour",
        brand: "OnColour",
        price: 2.30,
        regularPrice: 7.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38991%2F38991_1.png&MediaId=12525117&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Esmalte de uñas de colores vivos y secado rápido.",
        stock: 300,
        category: 'makeup',
        rating: 4.6,
        reviewCount: 1740
    },
    // --- NUEVOS PRODUCTOS FALTANTES PARA OFERTAS ---
    {
        id: 44960,
        name: "Acondicionador Rico Reparación Intensa DUOLOGI",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44960%2F44960_1.png",
        description: "Reparación intensa para cabello seco y dañado.",
        stock: 100,
        category: "hair",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 120
    },
    {
        id: 44961,
        name: "Acondicionador Ligero Volumen y Cuerpo DUOLOGI",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44961%2F44961_1.png",
        description: "Volumen y cuerpo para cabello fino.",
        stock: 100,
        category: "hair",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 95
    },
    {
        id: 47440,
        name: "Gel de Ducha Exfoliante Energizante Love Nature Simple Joys",
        brand: "Love Nature",
        price: 5.99,
        regularPrice: 12.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47440%2F47440_1.png",
        description: "Gel de ducha con partículas exfoliantes naturales.",
        stock: 150,
        category: "personal-care",
        rating: 4.6,
        reviewCount: 60
    },
    {
        id: 46987,
        name: "Crema de Manos Hidratante Love Nature",
        brand: "Love Nature",
        price: 2.99,
        regularPrice: 7.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46987%2F46987_1.png",
        description: "Hidratación suave con aroma fresco.",
        stock: 200,
        category: "personal-care",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 150
    },
    {
        id: 47009,
        name: "Jabón en Barra Love Nature Simple Joys",
        brand: "Love Nature",
        price: 1.99,
        regularPrice: 4.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47009%2F47009_1.png",
        description: "Jabón suave para uso diario.",
        stock: 250,
        category: "personal-care",
        rating: 4.7,
        reviewCount: 80
    },
    {
        id: 46642,
        name: "Jabón Líquido Manos y Cuerpo Limón y Verbena Essense & Co",
        brand: "Essense & Co",
        price: 15.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46642%2F46642_1.png",
        description: "Jabón líquido premium con aceites esenciales.",
        stock: 40,
        category: "personal-care",
        rating: 4.9,
        reviewCount: 110
    },
    {
        id: 46731,
        name: "Loción Manos y Cuerpo Limón y Verbena Essense & Co",
        brand: "Essense & Co",
        price: 16.99,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46731%2F46731_1.png",
        description: "Loción hidratante ligera y perfumada.",
        stock: 35,
        category: "personal-care",
        rating: 4.8,
        reviewCount: 90
    },
    {
        id: 45799,
        name: "Gel de Ducha Cardamomo y Flor de Algodón Essense & Co",
        brand: "Essense & Co",
        price: 15.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45799%2F45799_1.png",
        description: "Gel de ducha especiado y reconfortante.",
        stock: 30,
        category: "personal-care",
        rating: 4.7,
        reviewCount: 45
    },
    {
        id: 45800,
        name: "Loción Manos y Cuerpo Cardamomo y Flor de Algodón Essense & Co",
        brand: "Essense & Co",
        price: 16.99,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45800%2F45800_1.png",
        description: "Hidratación profunda con aroma sofisticado.",
        stock: 25,
        category: "personal-care",
        rating: 4.8,
        reviewCount: 50
    },
    {
        id: 47450,
        name: "Recambio Jabón Líquido Limón y Verbena Essense & Co",
        brand: "Essense & Co",
        price: 12.99,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47450%2F47450_1.png",
        description: "Recambio ecológico para tu jabón favorito.",
        stock: 60,
        category: "personal-care",
        rating: 4.9,
        reviewCount: 30
    },
    {
        id: 46801,
        name: "Divine Dark Velvet Eau de Parfum",
        brand: "Divine",
        price: 29.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Fragancia nocturna y misteriosa, edición limitada.",
        stock: 50,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 75
    },
    {
        id: 46968,
        name: "Crema de Manos y Cuerpo Milk & Honey Gold",
        brand: "Milk & Honey",
        price: 19.00,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46968%2F46968_1.png",
        description: "Nutrición legendaria con leche y miel orgánicas.",
        stock: 80,
        category: "personal-care",
        rating: 4.9,
        reviewCount: 300
    },
    {
        id: 46969,
        name: "Exfoliante de Azúcar Milk & Honey Gold",
        brand: "Milk & Honey",
        price: 14.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46969%2F46969_1.png",
        description: "Exfoliante de azúcar que deja la piel suave y radiante.",
        stock: 70,
        category: "personal-care",
        rating: 4.8,
        reviewCount: 210
    },
    {
        id: 46970,
        name: "Jabón Líquido Milk & Honey Gold",
        brand: "Milk & Honey",
        price: 12.99,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46970%2F46970_1.png",
        description: "Limpieza suave e hidratante.",
        stock: 90,
        category: "personal-care",
        rating: 4.8,
        reviewCount: 180
    },
    {
        id: 46971,
        name: "Champú Milk & Honey Gold",
        brand: "Milk & Honey",
        price: 9.99,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46971%2F46971_1.png",
        description: "Champú nutritivo para cabello brillante.",
        stock: 85,
        category: "hair",
        rating: 4.7,
        reviewCount: 140
    },
    {
        id: 36151,
        name: "Crema Universal con Aceite de Grosella Negra",
        brand: "Crema Universal",
        price: 3.99,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F36151%2F36151_1.png",
        description: "Bálsamo multiusos con aroma a grosella negra.",
        stock: 300,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 500
    },
    {
        id: 47878,
        name: "Esponja Konjac Exfoliante",
        brand: "Oriflame",
        price: 6.99,
        regularPrice: 10.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47878%2F47878_1.png",
        description: "Esponja natural para una limpieza profunda.",
        stock: 40,
        category: "accessories",
        rating: 4.5,
        reviewCount: 25
    },
    {
        id: 47677,
        name: "Cepillo Desenredante StylerPRO",
        brand: "Oriflame",
        price: 8.99,
        regularPrice: 12.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47677%2F47677_1.png",
        description: "Cepillo ideal para desenredar sin tirones.",
        stock: 60,
        category: "accessories",
        rating: 4.8,
        reviewCount: 110
    },
    {
        id: 47202,
        name: "Crema de Manos Dream Cream",
        brand: "Oriflame",
        price: 2.50,
        regularPrice: 6.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47202%2F47202_1.png",
        description: "Crema de manos tamaño bolso, ideal para llevar.",
        stock: 400,
        category: "personal-care",
        tag: "OFERTA",
        rating: 4.6,
        reviewCount: 800
    },
    {
        id: 153756,
        name: "Set Regalo Mister Giordani",
        brand: "Giordani Gold",
        price: 39.99,
        regularPrice: 65.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F153756%2F153756_1.png",
        description: "Set exclusivo con Eau de Toilette y Desodorante.",
        stock: 20,
        category: "men",
        tag: "SET",
        rating: 4.9,
        reviewCount: 15
    },
    {
        id: 153757,
        name: "Set Regalo Miss Giordani",
        brand: "Giordani Gold",
        price: 39.99,
        regularPrice: 65.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F153757%2F153757_1.png",
        description: "Set elegante con Eau de Parfum y Loción Corporal.",
        stock: 25,
        category: "perfume",
        tag: "SET",
        rating: 4.9,
        reviewCount: 20
    },
    {
        id: 47536,
        name: "Set Regalo Nordic Waters para Él",
        brand: "Nordic Waters",
        price: 34.99,
        regularPrice: 58.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47536%2F47536_1.png",
        description: "Frescura nórdica en un set de regalo.",
        stock: 30,
        category: "men",
        tag: "SET",
        rating: 4.8,
        reviewCount: 10
    },
    {
        id: 47538,
        name: "Set Regalo Eclat Femme Weekend",
        brand: "Eclat",
        price: 32.99,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47538%2F47538_1.png",
        description: "Elegancia parisina en un set festivo.",
        stock: 35,
        category: "perfume",
        tag: "SET",
        rating: 4.8,
        reviewCount: 18
    },
    {
        id: 20374,
        name: "Pack Bienestar",
        brand: "Wellness",
        price: 45.00,
        regularPrice: 60.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F20374%2F20374_1.png",
        description: "Pack completo de vitaminas y minerales.",
        stock: 50,
        category: "wellness",
        tag: "SET",
        rating: 4.9,
        reviewCount: 120
    },
    {
        id: 104,
        name: "Muestras de Fragancias (Pack de 5)",
        brand: "Oriflame",
        price: 2.00,
        regularPrice: 5.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F104%2F104_1.png",
        description: "Descubre tus nuevos aromas favoritos.",
        stock: 500,
        category: "perfume",
        rating: 4.5,
        reviewCount: 50
    },
    {
        id: 38497,
        name: "Divine Eau de Parfum",
        brand: "Divine",
        price: 29.99,
        regularPrice: 48.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2F38497_1.png",
        description: "Fragancia icónica para momentos divinos.",
        stock: 60,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 300
    },
    {
        id: 22442,
        name: "Crema Reafirmante Royal Velvet",
        brand: "Royal Velvet",
        price: 24.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F22442%2F22442_1.png",
        description: "Lujosa crema reafirmante con infusión de Iris Negro.",
        stock: 40,
        category: "skincare",
        rating: 4.9,
        reviewCount: 450
    },
    {
        id: 1440,
        name: "Bolsa de Regalo Pequeña",
        brand: "Oriflame",
        price: 1.50,
        regularPrice: 2.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F1440%2F1440_1.png",
        description: "Bolsa elegante para tus regalos.",
        stock: 1000,
        category: "accessories",
        rating: 4.7,
        reviewCount: 200
    }
];
